import { chromium } from '@playwright/test';
const OUT='/tmp/claude-0/-home-user-portfolio/2d0d34ac-2ff9-55f3-b689-20dc60d4a33e/scratchpad/shots';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const p = await b.newPage({ viewport:{width:1440,height:900} });
await p.goto('http://localhost:3100/', { waitUntil:'networkidle' });
await p.evaluate(()=>document.fonts.ready);
await p.emulateMedia({ media:'print' });
await p.waitForTimeout(700);
const h = await p.evaluate(()=>document.documentElement.scrollHeight);
console.log('print height:', h, '~pages:', Math.ceil(h/1123));
const t = await p.locator('#resume').innerText();
console.log('eyebrow gone:', !t.includes('06 /'), '| status line gone:', !/SHOWING ALL/i.test(t));
await p.screenshot({ path:`${OUT}/print-final-1440.png`, fullPage:true });
await b.close();
